//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_Travail3
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueListerQuantiteAccepteePourProjet
    {
        public int no_Piece { get; set; }
        public int no_Projet { get; set; }
        public string description_Piece { get; set; }
        public Nullable<int> quantiteAcceptee { get; set; }
    }
}
